### ISSUE TITLE
Definition der Serre-Klasse muss über kurze exakte Sequenzen sprechen

### ISSUE THREAD

**Issue by iblech** [timjb/presentations#2]
Die Sequenz `0 --> Z/(2) --> Z oplus Z/(2)` abelscher Gruppen ist exakt. Die mittlere Gruppe ist endlich. Die endlichen Gruppen bilden eine Serre-Klasse. Dann müsste auch die hintere Gruppe `Z oplus Z/(2)` endlich sein. Ist sie aber nicht. :-)

Die Bedingung `B in \C <==> A, C in \C` darf man also nur fordern, wenn `0 --> A --> B --> C --> 0` eine kurze exakte Sequenz ist (mit den Nullern am Rand).

**Comment by timjb** [comment]
Super, dass du das noch gemerkt dass! Riesendanke dafür! Hatte mir das im Kopf überlegt, aber wohl nur eine Richtung. Die Definition wird soweit ich dass sehe, auch richtig, wenn man das "<=>" durch ein "=>" ersetzt.

**Comment by iblech** [comment]
Jup, sie wird richtig, wenn man das "<==>" durch ein "<==" ersetzt. Genauer sind die folgenden Axiome an eine Klasse äquivalent:
1. Die Klasse enthält das Nullobjekt und ist abgeschlossen unter Subobjekten, Quotienten und Extensionen.
2. Die Klasse enthält das Nullobjekt und, für jede exakte Sequenz `A --> B --> C` mit `A` und `B` in der Klasse, liegt auch `B` in der Klasse.

Eine Klasse mit 2. erfüllt offensichtlich auch 1. Für die umgekehrte Richtung nutze die Epi-/Mono-Faktorisierungen von `A --> B` und `B --> C`, um eine kurze exakte Sequenz der Form `0 --> I --> B --> J --> 0` zu erhalten, in der `I` ein Quotient von `A` und `J` ein Unterobjekt von `C` ist.
